const materialCodes = {
  "00": [
    "TS",
  ],
  "TS": [
    "TSTP",
    "TSTT",
    "TSWZ",
  ],
  "TSTP": [
    "TSTP1",
    "TSTP2",
    "TSTP3",
    "TSTP4",
    "TSTP5",
    "TSTP6",
    "TSTP7",
    "TSTP8",
    "TSTP9",
    "TSTP10",
    "TSTP11",
  ],
  "TSTT": [
    "TSTT1",
    "TSTT2",
    "TSTT3",
    "TSTT4",
    "TSTT5",
  ],
  "TSWZ": [
    "TSWZ1",
    "TSWZ2",
  ],
}
const materialNames = {
  "TS": "Tworzywa sztuczne",
  "TSTP": "Tworzywa termoplastyczne",
  "TSTP1": "Poliolefiny: polietylen (PE), polipropylen (PP)",
  "TSTP2": "Polichlorek winylu (PVC)",
  "TSTP3": "Termoplasty na bazie styrenu: polistyren (PS), kopolimer akrylonitrylo-butadienowo-styrenowy (ABS), kopolimer akrylonitrylo-styrenowo-akrylowy (ASA), kopolimer styrenowo-akrylonitrylowy (SAN), kopolimer styrenu i bezwodnika maleinowego (SMA)",
  "TSTP4": "Poliamidy (PA)",
  "TSTP5": "Poliuretany (TPU)",
  "TSTP6": "Poliestry termoplastyczne: politereftalan butylenu (PBT), politereftalan etylenu (PET), politereftalan trimetylu (PTT), polinaftalan etylenu (PEN), polimery ciekłokrystaliczne (LCP)",
  "TSTP7": "Poliacetal (POM)",
  "TSTP8": "Eter polifenylenowy (PPE)",
  "TSTP9": "Elastomery termoplastyczne (TPEs): elastomery termoplastyczne olefinowe (TPE-O), elastomery termoplastyczne wulkanizowane dynamicznie (TPE-V), elastomery termoplastyczne poliestrowe (TPE-E), elastomery termoplastyczne styrenowe (TPE-S), elastomery termoplastyczne poliamidowe (TPE-A), elastomery termoplastyczne poliuretanowe (TPE-U)",
  "TSTP10": "Fluoropolimery: politetrafluoroetylen (PTFE), polifluorek winylidenu (PVDF), tetrafluoroetylen etylenu (ETFE), chlorotrifluoroetylen etylenu (ECTFE), tetrafluoroetylen-heksafluoropropylen i fluorek winylidenu (THV)",
  "TSTP11": "Inne tworzywa termoplastyczne: polimetakrylan metylu (PMMA), poliketony alifatyczne (APK)",
  "TSTT": "Tworzywa termoutwardzalne",
  "TSTT1": "Poliestry nienasycone (żywice UP)",
  "TSTT2": "Żywica fenolowo-formaldehydowa (PF)",
  "TSTT3": "Żywica epoksydowa (EP)",
  "TSTT4": "Poliuretany termoutwardzalne (PUR)",
  "TSTT5": "Inne tworzywa termoutwardzalne: żywice winyloestrowe (VP), żywice mocznikowo-formaldehydowe (UF), żywice melaminowo-formaldehydowe (MF)",
  "TSWZ": "Inne/Wzmocnienia",
  "TSWZ1": "Włókna szklane i mata szklana",
  "TSWZ2": "Inne: włókna naturalne, włókna aramidowe, włókna węglowe, włókna metalowe, wypełniacze (kreda, talk), nanokompozyty",
}
